---
title: "prof"
author: "Malaika Handa"
date: "December 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Set up

Load the libraries
```{r}
library(tidyverse)
library(lubridate)
```

Load the data
```{r}
prof = read_csv("prof.csv") %>% mutate(date = mdy(date))
```

## Just likes

Make the plot
```{r, fig.height = 7, fig.width = 15}
ggplot(data = prof,
       aes(x = date,
           y = likes)) +
  geom_line(size = 1) +
  labs(title = "Likes on Mali's profile pictures over time",
       x = "",
       y = "Number of Likes",
       color = "") +
  theme_bw()
```

Save the plot
```{r}
ggsave("likes.png")
```

## Likes and comments

```{r}
prof = data.frame(date = c(prof$date, prof$date),
                  type = c(rep("Likes", nrow(prof)), rep("Comments", nrow(prof))),
                  count = c(prof$likes, prof$comments))
```

Make the plot
```{r, fig.height = 7, fig.width = 15}
ggplot(data = prof,
       aes(x = date,
           y = count,
           color = type)) +
  geom_line(size = 1) +
  labs(title = "Mali's profile pictures over time",
       x = "",
       y = "Count",
       color = "") +
  theme_bw()
```

Save the plot
```{r}
ggsave("pics.png")
```